luthermonson/go-proxmox

nodes.go
types.go
virtual_machines.go
virtual_machines_test.go

- Brought VM actions in line with start/stop/suspend/reboot/resume functionality for containers.
- Minimal integration tests (only works with an existing VM, temporary until VM creation/deletion is working).

Added VM actions

---

containers.go
go.mod
go.sum
magefile.go
nodes.go
nodes_test.go
proxmox.go
types.go
virtual_machines.go
virtual_machines_test.go

this recreates the functionality in the xterm.js vnc web socket connection used by proxmox to talk to the host/qemu/lxc. This was mostly tested using the host but should be functional in containers out of the box and will be tested more with containers when i actually get to working on them.
the web socket has some prereqs you will need to see #25 for setup info and figure out how to get your guest vms to properly use the socket0 serial for tty output.

semi working termproxy/vncwebsocket endpoints

---

virtual_machines.go

I made a mistake yesterday, the resize endpoint does not return a task but a null value as it is a synchronous operation.

Correctly handle null return of disk resize endpoint

---

types.go
virtual_machines.go

I tried implementing the full range of parameters supported by those calls while I was at it.
For `Clone`, I kept newid exclusively in the Options structure in the end, since an implicit call to NextID as the default behavior makes sense and simplifies client usage in most cases.
For `MoveDisk`, I'm a bit torn on what to do with `disk` since it is mandatory but is also part of the JSON payload so I need it in the Options struct anyway. The current implementation now has two way to pass this information, either through the arg, or through the Options struct if the `disk` arg is empty. I could also systematically overwrite the struct value with the arg even when empty, or drop the arg altogether, which would make the struct mandatory in practice.

Rewrite Clone and MoveDisk qemu calls to support all endpoint parameters

---

types.go

I was missing a few fields for my own use, and figured it would be nice to extend this `VirtualMachineConfig` a bit further since I may need the rest later on anyway. Now I know this is a lot of fields, but even parallel ports have their use sometimes (though I hope I'll never have to go down this path myself).
I actually cut a few superfluous ones on the way. The endpoint spec seems to indicates IDE devices are limited to 4 and SATA to 6. SCSI on the other hand goes as far as 30. I let lists with unspecified limits at 10 as this seemed a reasonable default
The diff is a bit of a mess since I figured a struct as large as this warranted some reorganization rather than an endless unsorted list. I also added JSON tags everywhere and replaced the regexp compilations to do away with the …

Extend VM config to cover most documented fields

---

virtual_machine.go

Current implementation is missing support for vendor-data and network-config.
Vendor data is similar to user-data, but allows a clean separation of cloud-config scripts from infrastructure providers and clients. Network config is basically a netplan config file and is the recommended way to setup networking use-cases different from the default cloud-init behavior (DHCP on the first working interface).

Extend cloud-init ISO builder to include vendor-data and network-config

---

virtual_machine.go

I realized I didn't handle properly the case where vendor-data and network-config were empty. An empty vendor-data config file will not be doing much, but though unlikely as it is an invalid configuration and should just be discarded, an empty network-config has potential for inhibiting the default network cloud-init behavior and replacing it with nothing. As I would rather not leave this up to cloud-init implementation details, not creating the files at all seems a safer course.

Better handle the optionality of network-config and vendor-data

---

types.go

I have the following issue, in any host that has stopped VMs I get the string null as b, I added a regexp check for checking if we have a number and if not set str to "0"

make sure we get a number, it not we set 0

---

proxmox.go
virtual_machine.go

regrets were have returning nil nil, adding a noop error type in case this happens again and decided to ultimately ignore the returned task in cloud init func since there wasn't much benefit to waiting for it to get done if we do actually call it
fixes #68

adding noop error and ignoring task from addtag in cloudinit

---

types.go
types_test.go

* moving CPULimit to use new StringOrFloat64 type
* added tests around all `Or` types 
* fixed regex to allow all floats to be used as Or types
* fixed error checking throughout `Or` types to give error responses to parse/validation errors to catch future api issues instead of blindingly returning `0`
fixes #69

adding StringOrFloat64

---

types.go

I noticed a few useful fields are missing from cluster resources and VM configurations. This PR aims to fix that.

Add missing fields to virtual machine config and cluster resource

---

logger.go
mage/install/install.go
mage/test/test.go
proxmox.go
storage.go
tasks.go
tasks_test.go
tests/integration/tasks_test.go
tests/integration/virtual_machines_test.go
types.go
virtual_machine.go
virtual_machine_config.go

This PR aims to solve part of the warnings raised by the Goland IDE. Leaving aside a few potentially more controversial ones (like unused unexported functions or deferring without handling errors).

Fix warnings raised by Goland

---

pools.go
pools_test.go
tests/mocks/pve7x/pools.go
types.go

* removed PoolAPI in favor of top level `Pool(s)`
* added filter for cluster resources to Pool
* replaced `Create` with `NewPool`

refactor pools to drop PoolAPI and add pool resource filters

---

README.md
access.go
access_test.go
cluster.go
cluster_firewall.go
cluster_test.go
containers.go
nodes.go
nodes_network.go
nodes_network_test.go
nodes_test.go
pools.go
pools_test.go
proxmox.go
proxmox_test.go
storage.go
tasks.go
tests/integration/cluster_test.go
tests/integration/proxmox_test.go
types.go
virtual_machine.go
virtual_machine_test.go

Add context support across the whole API using a first argument design.

Add context support

---

cluster.go

cluster status requires sys.audit and being a part of the cluster call it errors out without access. this lets the cluster still come back which you can list but can't get status details

still return a cluster if no sys.audit access

---

containers.go
types.go

Hi, 
I'm currently working on a Kubernetes operator for Proxmox and am impressed by the "go-proxmox" project. I realized that cloning an LXC is not implemented by the client so my PR tries to have an implementation of LXC cloning.
Here is the relevant API documentation on [Proxmox](https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc/{vmid}/clone):

Add support for LXC clone

---

containers.go
types.go

This commit adds functionality for deleting the Container object(s).

Add delete function for containers(LXC)

---

containers.go
types.go

Add Config function for containers to for updating container resource(s)

feat: Add Config function for containers(LXC)

---

types.go

Following upstream API breakage in qemu-server 8.0.8
Reference upstream commit: 7f8c808772979f274cdfac1dc7264771a3b7a7ae

Fix qemu config memory field parsing

---

types.go
virtual_machine.go

Add missing flags to allow live migration, with local disks.
Those flags are not supposed to do anything with offline VM and shouldn't change the current behavior too much, except if someone relied on migration failing.

Fix live migrations

---

nodes.go
types.go

The PR aims to add download-url functionality on Proxmox API. Here is the relevant API documentation:
https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/storage/{storage}/download-url

Add support for download-url function on node/storage

---

nodes.go
storage.go
types.go

This PR tries to add a function to get all existing content from node's specified storage. 
The following API documentation:
https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/storage/{storage}/content

Add StorageContentGet function

---

storage.go

This PR aims to fix the issue generated by #111. The return object should be an array according to the API docs.

fix: Return array for Getcontent method

---

storage.go

This PR aims to add 'DeleteContent' method for storage objects. Here is the relevant API documentation:
https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/storage/{storage}/content/{volume}

✨feat: Add DeleteContent method for storage

---

storage.go
virtual_machine.go

This PR aims to have 'ConvertToTemplate' for VirtualMachine struct to enable VMs to be converted into templates via Proxmox API (/nodes/{node}/qemu/{vmid}/template).

✨feat: Add ConvertToTemplate method

---

types.go
virtual_machine.go

Fixed types according to proxmox API in AgentExecStatus struct

Fixed types in AgentExecStatus struct

---

containers.go
containers_test.go
nodes.go
tests/mocks/pve7x/nodes.go
types.go
virtual_machine_test.go

This PR aims to enhance LXC support for Proxmox. Here is the documentation of LXC(Containers) API.
https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/lxc

✨feat: Enhance support for containers

---

types.go
virtual_machine.go

Allow to pass arguments for command as an string slice.

Agent exec args

---

nodes.go
types.go
virtual_machine.go

Basic backup logic

---

virtual_machine.go

This PR:
- Adds a function `UnmountCloudInitISO` to unattach and delete the cloudinit iso.
Closes #127

Add function that Unmount Cloud ISO if not needed

---

virtual_machine.go

That caused a panic:
Fix the AgentExec func to return error if no pid, has returned.
`oup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/test-dev-control-plane-ptkhg" namespace="default" name="test-dev-control-plane-ptkhg" reconcileID="8013f2cd-4d25-4072-9c80-7d79af7191a4"
panic: interface conversion: interface {} is nil, not float64 [recovered]
panic: interface conversion: interface {} is nil, not float64
`

Fix AgentExec when no pid returned

---

types.go

fix: CPUInfo.MHZ type error

---

storage.go
tests/mocks/pve7x/nodes.go
types.go

This PR aims to add storage operations over the "/storage" API.

✨feat: Add cluster storage operations

---

cluster.go
cluster_test.go
tests/mocks/pve7x/cluster.go

The Proxmox API endpoint `/cluster/nextid` takes an optional argument `vmid` to check if the given ID is free.
This argument is not implemented in the existing `NextID` function. In order not to break the existing API, I have added a new function `isVMIDTaken`.
This is especially useful if you want to check for a VMID without having `VM.Audit` privileges on the whole cluster.

Add function CheckID

---

types.go

This PR tries to add a CIUpgrade field to VirtualMachineConfig struct.
Here is the relevant API doc:
https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/config
The field can be found as "ciupgrade" and also here is an example output from Proxmox cluster.
`{"boot":"order=scsi0","cipassword":"**********","ciupgrade":1,"ciuser":"ubuntu","cores":2,"digest":"b1d4d4d59a8bb982a9b173c3f5741207b0869a79","ide2":"local-lvm:vm-105-cloudinit,media=cdrom","memory":"2048","meta":"creation-qemu=8.1.5,ctime=1724765699","name":"virtualmachinetemplate-sample","nameserver":"10.0.0.1 10.0.0.2","net0":"virtio=BC:24:11:A7:27:31,bridge=vmbr0","scsi0":"local-lvm:base-105-disk-0,size=2252M","scsihw":"virtio-scsi-pci","searchdomain":"alperen.cloud","smbios1":"uuid=36e481f6-430b-4baf-b238-19dd0d891 …

feat: Add CIUpgrade field on VirtualMachineConfig

---

containers.go
containers_test.go
tests/mocks/pve7x/nodes.go
virtual_machine.go
virtual_machine_test.go

The `Clone` functions (`Container.Clone` and `VM.Clone`), when called with `CloneOptions.NewID` set, return 0 instead of the `NewID`.
I extended the tests. Updated `TestContainerClone` and new `TestVirtualMachineClone` tests fail without this fix.

Fix return value of `Clone` functions when `CloneOptions.NewID` is set

---

containers.go
nodes.go
proxmox.go
tests/integration/nodes_test.go
tests/integration/proxmox_test.go
tests/integration/storage_test.go
tests/integration/tasks_test.go
tests/integration/virtual_machines_test.go
types.go
virtual_machine.go

Hi, recently I opened two issues:
#147: This issue was caused by a breakline that prevented me from using xtermjs.org. After removing the breakline, it worked fine.
#148: I was unable to use VNC at all.
After some research, I decided to re-implement the solution since I use this library frequently, and these features are important to me.
Additionally, I created a proof of concept (POC), hosted in this repository: https://github.com/ricardoalcantara/go-proxmox-term-and-vnc, which I will soon incorporate into my own project.
I would like to contribute my work and I'm open to further discussion.

Re-Implementation of Term and VNC Features.

---

cluster_firewall.go
cluster_test.go
nodes_network.go
tasks.go
types.go
virtual_machine.go
virtual_machine_config.go

Fix various linting warnings

---

virtual_machine.go

Drops the use of the QMP Status field when determining if a VM is running, stopped, paused or hibernated.

fix: do not compare optional QMP Status field when determining VM status

---

container_config.go
containers.go
containers_test.go
tests/mocks/pve7x/nodes.go
types.go

Shamelessly copied TagsSlice and Tag helper functions from VirtualMachine implementation
Add Indexed fields helper maps

Quality of life features for ContainerConfig

---

virtual_machine.go
virtual_machine_test.go

Found a small bug in the VirtualMachine.IsPaused function:
The condition in the IsPaused function checks whether the VM is running, not whether it's in a pause state.

Fix VirtualMachine.IsPaused

---

container_config.go

minor typo corrections (sorry)

fix typos in function comments

---

virtual_machine.go
virtual_machine_test.go

The fix for #139 (#166) breaks some VirtualMachine state functions.
I have tried to implement the functions in a way that works with and without a `VirtualMachine.QMPStatus`. Without a `QMPStatus`, we can't be sure of the paused state (because the `Status` of a paused VM is still `Running`).

Fix VM state functions

---

types.go

Fixed a spelling error in ContainerConfig's unprivileged struct tag

correct typo in containerconfig field

---

proxmox.go
types.go
virtual_machine.go

This PR aims to add functionality to support query parameters on GET requests.

feat: Add query parameters support for GET method

---

containers.go
types.go
virtual_machine.go

Introduce new methods to manage Firewall IPSet and IPSetEntries for both VirtualMachine and Container. Functions include creation, retrieval, updating, and deletion of IPSets and their entries. Added corresponding struct types for IPSet and IPSetEntry handling options.

Adding firewall IPSet functionality 

---

nodes_network.go
nodes_network_test.go
tests/mocks/pve8x/nodes.go
types.go

See #200 for reasoning.
This PR adds a new function `NetworksOfType` to enable listing of networks by a specific type. Requesting a specific type can return more results than just requesting all networks, so this allows you to query all types of networks.
One caveat is that in `NodeNetwork`, I needed to change the `Active` field from `int` to `StringOrInt` since for some reason some of Proxmox's responses when specifying type are set to strings rather than ints. This may be a breaking change, although StringOrInt is an int under the hood so in most cases it should work as-is. Open to suggestions here.

Add listing of network interfaces by type
